version: "3"

services:
  db:
    image: postgres
    container_name: db
    restart: always
    networks:
      - web_net
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      #set these in the .env file as key_name=value
      - POSTGRES_USER=${pg_user}
      - POSTGRES_PASSWORD=${pguser_password}
      - POSTGRES_DB=${pgdb_name}

  app:
    build:
      context: app
    container_name: app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - web_net
    volumes:
      - ./volumes/app/config:/mysite/config:rw
      - ./volumes/app/log:/mysite/log:rw
    environment:
      #set these in the .env file
      - pg_user=${pg_user}
      - pg_pass=${pguser_password}
      - pg_db=${pgdb_name}
      - django_port=${django_port}
      - django_admin=${django_admin}
      - django_email=${django_email}
      - django_password=${django_password}

  web:
    build: web
    container_name: web
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web_net
    read_only: true
    restart: unless-stopped
    volumes:
      # This directory must have cert files if you want to enable SSL
      - ./volumes/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - django_port=${django_port}

networks:
  web_net: {}
